Start;
input a,b,c;
d=(b*b)-(4*a*c);
if d=0; 
then x1=b/(2*a) output (x1=x2);
else if (d<0);
then x1=-b/(2*a) output (x1);
x2=sqrt(-d)(2*a) output (x2);
else if (d>0);
then x1=-b+sqrt(d)/(2*a) output (x1);
x2=-b-sqrt(d)/(2*a) output (x2);
end;
